name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    env:
      JULIA_NUM_THREADS: 2
    strategy:
      fail-fast: true
      matrix:
        experimental: [false]
        julia-version:
          - '1.10'
          - '1.12'
        os:
          - ubuntu-latest
        julia-arch:
          - x64
        include:
          - julia-version: '1.12'
            julia-arch: aarch64
            os: ubuntu-24.04-arm
            experimental: true
          - julia-version: 'pre'
            julia-arch: x64
            os: ubuntu-latest
            experimental: true
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
        with:
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
      - name: Precompile project
        run: |
          julia --project -e '
            using Pkg
            Pkg.instantiate()
            Pkg.precompile()
          '
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }} # required

# vim: shiftwidth=2
